### ISSUE TITLE
KeyError: 'encoder_embeddings'

### ISSUE THREAD

**Issue by einsqing** [TMElyralab/MuseTalk#1]
Traceback (most recent call last):
  File "/root/anaconda3/envs/musetalk/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/musetalk/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/heqing/test/MuseTalk/scripts/inference.py", line 141, in <module>
    main(args)
  File "/root/anaconda3/envs/musetalk/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/heqing/test/MuseTalk/scripts/inference.py", line 55, in main
    whisper_feature = audio_processor.audio2feat(audio_path)
  File "/home/heqing/test/MuseTalk/musetalk/whisper/audio2feature.py", line 99, in audio2feat
    encoder_embeddings = emb['encoder_embeddings']
KeyError: 'encoder_embeddings'

**Comment by itechmusic** [comment]
Hi there, are u running the example testcase or your own data?

Did you install a modified version of `whisper` using this command https://github.com/TMElyralab/MuseTalk?tab=readme-ov-file#whisper ?

> Traceback (most recent call last): File "/root/anaconda3/envs/musetalk/lib/python3.10/runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "/root/anaconda3/envs/musetalk/lib/python3.10/runpy.py", line 86, in _run_code exec(code, run_globals) File "/home/heqing/test/MuseTalk/scripts/inference.py", line 141, in main(args) File "/root/anaconda3/envs/musetalk/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/home/heqing/test/MuseTalk/scripts/inference.py", line 55, in main whisper_feature = audio_processor.audio2feat(audio_path) File "/home/heqing/test/MuseTalk/musetalk/whisper/audio2feature.py", line 99, in audio2feat encoder_embeddings = emb['encoder_embeddings'] KeyError: 'encoder_embeddings'
