### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by yunasuka** [TMElyralab/MuseTalk#109]
win11 and cuda11.7, I didn't do anything wrong. 

`(venv) PS D:\mypy\musetalk> python -m scripts.inference --inference_config configs/inference/test.yaml
Loads checkpoint by local backend from path: ./models/dwpose/dw-ll_ucoco_384.pth
cuda start
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\mypy\musetalk\scripts\inference.py", line 13, in <module>
    from musetalk.utils.preprocessing import get_landmark_and_bbox,read_imgs,coord_placeholder
  File "D:\mypy\musetalk\musetalk\utils\preprocessing.py", line 23, in <module>
    fa = FaceAlignment(LandmarksType._2D, flip_input=False,device=device)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mypy\musetalk\musetalk/utils\face_detection\api.py", line 69, in __init__
    self.face_detector = face_detector_module.FaceDetector(device=device, verbose=verbose)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mypy\musetalk\musetalk/utils\face_detection\detection\sfd\sfd_detector.py", line 22, in __init__
    model_weights = load_url(models_urls['s3fd'])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mypy\musetalk\venv\Lib\site-packages\torch\hub.py", line 750, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mypy\musetalk\venv\Lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mypy\musetalk\venv\Lib\site-packages\torch\serialization.py", line 1051, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
RuntimeError: unexpected EOF, expected 296278 more bytes. The file might be corrupted.`

**Comment by czk32611** [comment]
Plz check whether https://github.com/TMElyralab/MuseTalk/issues/77 helps and let us know.

**Comment by yunasuka** [comment]
> Plz check whether #77 helps and let us know.请检查 #77 是否有所帮助，并告知我们。

It's done. Thank you.
