### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by tmfql123** [TMElyralab/MuseTalk#126]
```
please download ffmpeg-static and export to FFMPEG_PATH.
For example: export FFMPEG_PATH=/musetalk/ffmpeg-4.4-amd64-static
Loads checkpoint by local backend from path: ./models/dwpose/dw-ll_ucoco_384.pth
cuda start
Downloading: "https://www.adrianbulat.com/downloads/python-fan/s3fd-619a316812.pth" to /root/.cache/torch/hub/checkpoints/s3fd-619a316812.pth
  0%|          | 0.00/85.7M [00:00<?, ?B/s]
  0%|          | 32.0k/85.7M [00:00<06:26, 233kB/s]
  0%|          | 96.0k/85.7M [00:00<04:03, 368kB/s]
  0%|          | 208k/85.7M [00:00<02:37, 570kB/s] 
  0%|          | 432k/85.7M [00:00<01:30, 985kB/s]
  1%|          | 880k/85.7M [00:00<00:49, 1.80MB/s]
  2%|▏         | 1.73M/85.7M [00:00<00:25, 3.39MB/s]
  4%|▍         | 3.50M/85.7M [00:00<00:13, 6.56MB/s]
  8%|▊         | 6.98M/85.7M [00:01<00:06, 12.7MB/s]
 13%|█▎        | 10.8M/85.7M [00:01<00:04, 17.5MB/s]
 17%|█▋        | 14.7M/85.7M [00:01<00:03, 20.7MB/s]
 22%|██▏       | 18.6M/85.7M [00:01<00:03, 23.0MB/s]
 26%|██▌       | 22.4M/85.7M [00:01<00:02, 24.6MB/s]
 31%|███       | 26.3M/85.7M [00:01<00:02, 25.7MB/s]
 35%|███▌      | 30.2M/85.7M [00:01<00:02, 26.4MB/s]
 40%|███▉      | 34.0M/85.7M [00:02<00:02, 26.9MB/s]
 44%|████▍     | 37.8M/85.7M [00:02<00:01, 27.1MB/s]
 49%|████▊     | 41.8M/85.7M [00:02<00:01, 27.6MB/s]
 53%|█████▎    | 45.6M/85.7M [00:02<00:01, 27.6MB/s]
 58%|█████▊    | 49.4M/85.7M [00:02<00:01, 27.8MB/s]
 62%|██████▏   | 53.2M/85.7M [00:02<00:01, 27.8MB/s]
 67%|██████▋   | 57.1M/85.7M [00:03<00:01, 27.9MB/s]
 71%|███████   | 60.9M/85.7M [00:03<00:00, 27.8MB/s]
 76%|███████▌  | 64.8M/85.7M [00:03<00:00, 27.9MB/s]
 80%|████████  | 68.6M/85.7M [00:03<00:00, 28.0MB/s]
 85%|████████▍ | 72.5M/85.7M [00:03<00:00, 28.0MB/s]
 89%|████████▉ | 76.3M/85.7M [00:03<00:00, 28.0MB/s]
 94%|█████████▎| 80.2M/85.7M [00:03<00:00, 27.9MB/s]
 98%|█████████▊| 84.0M/85.7M [00:04<00:00, 27.8MB/s]
100%|██████████| 85.7M/85.7M [00:04<00:00, 22.3MB/s]
RUN: predict
sh: 1: Syntax error: "(" unexpected
video in 30.0 FPS, audio idx in 50FPS
extracting landmarks...time consuming
reading images...
get key_landmark and face bounding boxes with the default value
********************************************bbox_shift parameter adjustment**********************************************************
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
Traceback (most recent call last):
File "/root/.pyenv/versions/3.11.9/lib/python3.11/site-packages/cog/server/worker.py", line 221, in _predict
result = predict(**payload)
^^^^^^^^^^^^^^^^^^
File "/src/predict.py", line 139, in predict
video_path =  m.main(args)
^^^^^^^^^^^^
File "/root/.pyenv/versions/3.11.9/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/src/scripts/main.py", line 81, in main
coord_list, frame_list = get_landmark_and_bbox(input_img_list, bbox_shift)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/src/musetalk/utils/preprocessing.py", line 134, in get_landmark_and_bbox
print(f"Total frame:「{len(frames)}」 Manually adjust range : [ -{int(sum(average_range_minus) / len(average_range_minus))}~{int(sum(average_range_plus) / len(average_range_plus))} ] , the current value: {upperbondrange}")
~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
```

I set the length of the video and audio to be the same, but ZeroDivisionError occurs.
How can I get results?
Thank you.

**Comment by 11whitewater** [comment]
你好，请问解决了吗？在对视频进行超分后，我遇到了同样的报错，但是原输入视频是能正常运行的

**Comment by czk32611** [comment]
一般是人脸检测失败了
