### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by 11whitewater** [TMElyralab/MuseTalk#132]
对输入视频进行超分处理后，视频分辨率变为810*720，但运行代码会出现报错ZeroDivisionError: division by zero，具体报错情况如下所示，希望可以得到解答，谢谢！！
Traceback (most recent call last):

  File "D:\BaiduNetdiskDownload\MuseTalk\DUDU-Lab_MuseTalk_Win_v1.0\.ai\lib\runpy.py", line 196, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "D:\BaiduNetdiskDownload\MuseTalk\DUDU-Lab_MuseTalk_Win_v1.0\.ai\lib\runpy.py", line 86, in _run_code

    exec(code, run_globals)

  File "D:\BaiduNetdiskDownload\MuseTalk\DUDU-Lab_MuseTalk_Win_v1.0\scripts\inference.py", line 145, in <module>

    main(args)

  File "D:\BaiduNetdiskDownload\MuseTalk\DUDU-Lab_MuseTalk_Win_v1.0\.ai\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context

    return func(*args, **kwargs)

  File "D:\BaiduNetdiskDownload\MuseTalk\DUDU-Lab_MuseTalk_Win_v1.0\scripts\inference.py", line 67, in main

    coord_list, frame_list = get_landmark_and_bbox(input_img_list, bbox_shift)

  File "D:\BaiduNetdiskDownload\MuseTalk\DUDU-Lab_MuseTalk_Win_v1.0\musetalk\utils\preprocessing.py", line 93, in get_landmark_and_bbox

    print(f"Total frame:「{len(frames)}」 Manually adjust range : [ -{int(sum(average_range_minus) / len(average_range_minus))}~{int(sum(average_range_plus) / len(average_range_plus))} ] , the current value: {upperbondrange}")

ZeroDivisionError: division by zero

********************************************bbox_shift parameter adjustment**********************************************************
![image](https://github.com/TMElyralab/MuseTalk/assets/125780042/f00d9aeb-0f67-47f0-969c-2db9c965c952)

**Comment by 11whitewater** [comment]
没超分前输入视频分辨率为448*398，是可以正常进行唇形合成的，以及当使用非正脸视频（例如侧面）时也会出现同样的报错

**Comment by czk32611** [comment]
应该是有一些帧没有识别出人脸
