### ISSUE TITLE
1.模型路径问题？ 2.网络连接问题？3.加速器命令行工具错误？我在使用魔法啊，但是连接不上Hunggingface的模型。

### ISSUE THREAD

**Issue by ImCVer** [TMElyralab/MuseTalk#160]
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
2024-08-07 14:16:56.205065: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-08-07 14:16:56.225896: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-07 14:16:56.573087: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/musetalk/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 380, in load_config
    config_file = hf_hub_download(
  File "/home/ubuntu/anaconda3/envs/musetalk/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/musetalk/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/ubuntu/anaconda3/envs/musetalk/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '../models/sd-vae-ft-mse/'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/MuseTalk-train_codes/train_codes/train.py", line 666, in <module>
    main()
  File "/home/ubuntu/MuseTalk-train_codes/train_codes/train.py", line 258, in main
    vae = AutoencoderKL.from_pretrained(args.pretrained_model_name_or_path, subfolder='vae')
  File "/home/ubuntu/anaconda3/envs/musetalk/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/musetalk/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 567, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "/home/ubuntu/anaconda3/envs/musetalk/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/musetalk/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 415, in load_config
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like ../models/sd-vae-ft-mse/ is not the path to a directory containing a config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/musetalk/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/envs/musetalk/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/home/ubuntu/anaconda3/envs/musetalk/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1057, in launch_command
    simple_launcher(args)
  File "/home/ubuntu/anaconda3/envs/musetalk/lib/python3.10/site-packages/accelerate/commands/launch.py", line 673, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ubuntu/anaconda3/envs/musetalk/bin/python', 'train.py', '--mixed_precision=fp16', '--unet_config_file=../models/musetalk/musetalk.json', '--pretrained_model_name_or_path=../models/sd-vae-ft-mse/', '--data_root=../data', '--train_batch_size=256', '--gradient_accumulation_steps=16', '--gradient_checkpointing', '--max_train_steps=100000', '--learning_rate=5e-05', '--max_grad_norm=1', '--lr_warmup_steps=0', '--output_dir=output', '--val_out_dir=val', '--testing_speed', '--checkpointing_steps=2000', '--validation_steps=2000', '--reconstruction', '--resume_from_checkpoint=latest', '--use_audio_length_left=2', '--use_audio_length_right=2', '--whisper_model_type=tiny', '--train_json=../train.json', '--val_json=../val.json', '--lr_scheduler=cosine']' returned non-zero exit status 1.

**Comment by czk32611** [comment]
需要提前下载好模型

**Comment by zhangziliang04** [comment]
手动下载吧。提前存储到对应目录下面。
