### ISSUE TITLE
FileNotFoundError: ./models/dwpose/dw-ll_ucoco_384.pth can not be found.

### ISSUE THREAD

**Issue by Asukaandjst** [TMElyralab/MuseTalk#165]
(musetalk) H:\MuseTalk\MuseTalk> python -m scripts.inference --inference_config configs/inference/test.yaml
please download ffmpeg-static and export to FFMPEG_PATH.
For example: export FFMPEG_PATH=/musetalk/ffmpeg-4.4-amd64-static
Loads checkpoint by local backend from path: ./models/dwpose/dw-ll_ucoco_384.pth
Traceback (most recent call last):
  File "H:\miniconda3\envs\musetalk\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "H:\miniconda3\envs\musetalk\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "H:\MuseTalk\MuseTalk\scripts\inference.py", line 13, in <module>
    from musetalk.utils.preprocessing import get_landmark_and_bbox,read_imgs,coord_placeholder
  File "H:\MuseTalk\MuseTalk\musetalk\utils\preprocessing.py", line 19, in <module>
    model = init_model(config_file, checkpoint_file, device=device)
  File "H:\miniconda3\envs\musetalk\lib\site-packages\mmpose\apis\inference.py", line 110, in init_model
    ckpt = load_checkpoint(model, checkpoint, map_location='cpu')
  File "H:\miniconda3\envs\musetalk\lib\site-packages\mmengine\runner\checkpoint.py", line 636, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "H:\miniconda3\envs\musetalk\lib\site-packages\mmengine\runner\checkpoint.py", line 548, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "H:\miniconda3\envs\musetalk\lib\site-packages\mmengine\runner\checkpoint.py", line 330, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "H:\miniconda3\envs\musetalk\lib\site-packages\mmengine\runner\checkpoint.py", line 346, in load_from_local
    raise FileNotFoundError(f'{filename} can not be found.')
FileNotFoundError: ./models/dwpose/dw-ll_ucoco_384.pth can not be found.

**Comment by Asukaandjst** [comment]
But in fact it does exist in the path \musetalk\models\dwpose

**Comment by zhangziliang04** [comment]
相对路径的问题，你把models的位置，上提一级，到项目的跟文件夹即可。

**Comment by HuangYongHang1** [comment]
你只需要找到那个文件preprocession.py然后对这个变量进行修改，checkpoint_file = './musetalk/models/dwpose/dw-ll_ucoco_384.pth'就可以解决，后面的其它路径问题也都是这样解决的，非常好用
