### ISSUE TITLE
实时推理脚本推理时脸部和掩码形状不匹配

### ISSUE THREAD

**Issue by ultranationalism** [TMElyralab/MuseTalk#171]
第一次推理的时候，由于没有preparation，可以正常推理。但是当不重新创建avatars的时候，就会报错。
> ace_large.size=(290, 290)
mask_image.size=(296, 296)
Exception in thread Thread-4 (process_frames):
Traceback (most recent call last):
  File "C:\Users\ultra\.conda\envs\musetalk\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\ultra\.conda\envs\musetalk\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\ultra\Desktop\project\MuseTalk\scripts\realtime_inference.py", line 221, in process_frames
    combine_frame = get_image_blending(ori_frame,res_frame,bbox,mask,mask_crop_box)
  File "C:\Users\ultra\Desktop\project\MuseTalk\.\musetalk\utils\blending.py", line 100, in get_image_blending
    body.paste(face_large, crop_box[:2], mask_image)
  File "C:\Users\ultra\.conda\envs\musetalk\lib\site-packages\PIL\Image.py", line 1847, in paste
    self.im.paste(im, box, mask.im)
ValueError: images do not match

报错部分：

    def get_image_blending(image,face,face_box,mask_array,crop_box):
    body = Image.fromarray(image[:,:,::-1])
    face = Image.fromarray(face[:,:,::-1])

    x, y, x1, y1 = face_box
    x_s, y_s, x_e, y_e = crop_box
    face_large = body.crop(crop_box)

    mask_image = Image.fromarray(mask_array)
    mask_image = mask_image.convert("L")
    face_large.paste(face, (x-x_s, y-y_s, x1-x_s, y1-y_s))
    if face_large.size!=mask_image.size:
        print(f"{face_large.size=}\n{mask_image.size=}")
    body.paste(face_large, crop_box[:2], mask_image)
    body = np.array(body)
    return body[:,:,::-1]

**Comment by ultranationalism** [comment]
抱歉，是我的问题，我把读取

**Comment by ultranationalism** [comment]
抱歉，是我的问题，我把读取改成多线程，导致文件队列错乱
