### ISSUE TITLE
nodes: D:\comfyui\ComfyUI\models\diffusers\TMElyralab/MuseTalk/dwpose/dw-ll_ucoco_384.pth can not be found. and no found llama_cpp模块

### ISSUE THREAD

**Issue by lindongyue7** [TMElyralab/MuseTalk#177]
C:\Users\PC\miniconda3\Lib\site-packages\mmengine\optim\optimizer\zero_optimizer.py:11: DeprecationWarning: `TorchScript` support for functional optimizers is deprecated and will be removed in a future PyTorch release. Consider using the `torch.compile` optimizer instead.
  from torch.distributed.optim import \
Loads checkpoint by local backend from path: D:\comfyui\ComfyUI\models\diffusers\TMElyralab/MuseTalk/dwpose/dw-ll_ucoco_384.pth
Traceback (most recent call last):
  File "D:\comfyui\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\comfyui\ComfyUI\custom_nodes\ComfyUI-MuseTalk\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "D:\comfyui\ComfyUI\custom_nodes\ComfyUI-MuseTalk\nodes.py", line 26, in <module>
    from musetalk.utils.preprocessing import get_landmark_and_bbox,read_imgs,coord_placeholder
  File "D:\comfyui\ComfyUI/custom_nodes/ComfyUI-MuseTalk\musetalk\utils\preprocessing.py", line 28, in <module>
    model = init_model(config_file, checkpoint_file, device=device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\miniconda3\Lib\site-packages\mmpose\apis\inference.py", line 110, in init_model
    ckpt = load_checkpoint(model, checkpoint, map_location='cpu')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\miniconda3\Lib\site-packages\mmengine\runner\checkpoint.py", line 636, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\miniconda3\Lib\site-packages\mmengine\runner\checkpoint.py", line 548, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\miniconda3\Lib\site-packages\mmengine\runner\checkpoint.py", line 330, in load_checkpoint
    return checkpoint_loader(filename, map_location)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\miniconda3\Lib\site-packages\mmengine\runner\checkpoint.py", line 346, in load_from_local
    raise FileNotFoundError(f'{filename} can not be found.')
FileNotFoundError: D:\comfyui\ComfyUI\models\diffusers\TMElyralab/MuseTalk/dwpose/dw-ll_ucoco_384.pth can not be found.

Cannot import D:\comfyui\ComfyUI\custom_nodes\ComfyUI-MuseTalk module for custom nodes: D:\comfyui\ComfyUI\models\diffusers\TMElyralab/MuseTalk/dwpose/dw-ll_ucoco_384.pth can not be found.
[ReActor] - STATUS - Running v0.5.1-a6 in ComfyUI
Torch version: 2.4.0+cu124
找不到llama_cpp模块
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...

**Comment by Jeiyoon** [comment]
I've encountered same problem 😢
