### ISSUE TITLE
运行案例的时候加载face-parse-bisent报错

### ISSUE THREAD

**Issue by dabaonidetou** [TMElyralab/MuseTalk#22]
(venv1) root@3bdaf96b00b0:/workspace/MuseTalk# python -m scripts.inference --inference_config configs/inference/test.yaml 
add ffmpeg to path
Loads checkpoint by local backend from path: ./models/dwpose/dw-ll_ucoco_384.pth
cuda start
Traceback (most recent call last):
  File "/opt/conda/envs/musev/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/musev/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/MuseTalk/scripts/inference.py", line 13, in <module>
    from musetalk.utils.preprocessing import get_landmark_and_bbox,read_imgs,coord_placeholder
  File "/workspace/MuseTalk/musetalk/utils/preprocessing.py", line 23, in <module>
    fa = FaceAlignment(LandmarksType._2D, flip_input=False,device=device)
  File "/workspace/MuseTalk/musetalk/utils/face_detection/api.py", line 69, in __init__
    self.face_detector = face_detector_module.FaceDetector(device=device, verbose=verbose)
  File "/workspace/MuseTalk/musetalk/utils/face_detection/detection/sfd/sfd_detector.py", line 22, in __init__
    model_weights = load_url(models_urls['s3fd'])
  File "/workspace/MuseTalk/venv1/lib/python3.10/site-packages/torch/hub.py", line 750, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/workspace/MuseTalk/venv1/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/workspace/MuseTalk/venv1/lib/python3.10/site-packages/torch/serialization.py", line 1051, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
RuntimeError: unexpected EOF, expected 1202694 more bytes. The file might be corrupted.

**Comment by itechmusic** [comment]
> (venv1) root@3bdaf96b00b0:/workspace/MuseTalk# python -m scripts.inference --inference_config configs/inference/test.yaml add ffmpeg to path Loads checkpoint by local backend from path: ./models/dwpose/dw-ll_ucoco_384.pth cuda start Traceback (most recent call last): File "/opt/conda/envs/musev/lib/python3.10/runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "/opt/conda/envs/musev/lib/python3.10/runpy.py", line 86, in _run_code exec(code, run_globals) File "/workspace/MuseTalk/scripts/inference.py", line 13, in from musetalk.utils.preprocessing import get_landmark_and_bbox,read_imgs,coord_placeholder File "/workspace/MuseTalk/musetalk/utils/preprocessing.py", line 23, in fa = FaceAlignment(LandmarksType._2D, flip_input=False,device=device) File "/workspace/MuseTalk/musetalk/utils/face_detection/api.py", line 69, in **init** self.face_detector = face_detector_module.FaceDetector(device=device, verbose=verbose) File "/workspace/MuseTalk/musetalk/utils/face_detection/detection/sfd/sfd_detector.py", line 22, in **init** model_weights = load_url(models_urls['s3fd']) File "/workspace/MuseTalk/venv1/lib/python3.10/site-packages/torch/hub.py", line 750, in load_state_dict_from_url return torch.load(cached_file, map_location=map_location) File "/workspace/MuseTalk/venv1/lib/python3.10/site-packages/torch/serialization.py", line 815, in load return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args) File "/workspace/MuseTalk/venv1/lib/python3.10/site-packages/torch/serialization.py", line 1051, in _legacy_load typed_storage._untyped_storage._set_from_file( RuntimeError: unexpected EOF, expected 1202694 more bytes. The file might be corrupted.

Hello，看起来是下载并加载s3fd人脸检测模型时报错`model_weights = load_url(models_urls['s3fd'])`。可以看一下`musetalk/utils/face_detection/detection/sfd`下的`s3fd.pth`自动下载是否成功
