### ISSUE TITLE
使用 MuseV 对图片生成视频，然后再用 realtime 模式生成 avator 会产生错误 ValueError: height and width must be > 0

### ISSUE THREAD

**Issue by Phoenix500526** [TMElyralab/MuseTalk#224]
realtime.yaml 文件设置如下：
```yaml
avator_1:
 preparation: True
 bbox_shift: 5
 video_path: "data/video/panpan.mp4"
 audio_clips:
     audio_0: "data/audio/yongen.wav"
     audio_1: "data/audio/sun.wav"
```

执行以下命令：
```bash
python -m scripts.realtime_inference --inference_config configs/inference/realtime.yaml
```

Traceback (most recent call last):
  File "/home/phoenix/miniconda3/envs/musetalk/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/phoenix/miniconda3/envs/musetalk/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/phoenix/MuseTalk/scripts/realtime_inference.py", line 322, in <module>
    avatar = Avatar(
  File "/home/phoenix/miniconda3/envs/musetalk/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/phoenix/miniconda3/envs/musetalk/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 129, in <lambda>
    func = cast(F, lambda *args, **kwargs: orig_func(*args, **kwargs))
  File "/home/phoenix/MuseTalk/scripts/realtime_inference.py", line 72, in __init__
    self.init()
  File "/home/phoenix/MuseTalk/scripts/realtime_inference.py", line 84, in init
    self.prepare_material()
  File "/home/phoenix/MuseTalk/scripts/realtime_inference.py", line 177, in prepare_material
    mask,crop_box = get_image_prepare_material(frame,face_box)
  File "/home/phoenix/MuseTalk/musetalk/utils/blending.py", line 73, in get_image_prepare_material
    mask_image = face_seg(face_large)
  File "/home/phoenix/MuseTalk/musetalk/utils/blending.py", line 23, in face_seg
    seg_image = seg_image.resize(image.size)
  File "/home/phoenix/miniconda3/envs/musetalk/lib/python3.10/site-packages/PIL/Image.py", line 2365, in resize
    return self._new(self.im.resize(size, resample, box))
ValueError: height and width must be > 0

**Comment by luxiongx** [comment]
有几帧画面没检测到人脸。

**Comment by MrWangMrsLu** [comment]
我用剪影重新编辑了一下视频，分辨率改成4k的可以了

**Comment by praymich** [comment]
> 有几帧画面没检测到人脸。

没检测到人脸的，代码怎么处理一下好一点呢？

**Comment by Lyhlyq** [comment]
您好，您这个问题怎么解决的 @praymich

**Comment by praymich** [comment]
> 您好，您这个问题怎么解决的 [@praymich](https://github.com/praymich)

没检测到人脸跳过对应帧就行

**Comment by Lyhlyq** [comment]
@praymich 谢谢啦
