### ISSUE TITLE
实时生成视频时出现ValueError错误

### ISSUE THREAD

**Issue by BIGshuaishuaishuai** [TMElyralab/MuseTalk#233]
报错信息：
```
541
  1%|▍                                                            | 1/136 [00:00<01:59,  1.13it/s]Exception in thread Thread-2 (process_frames):
Traceback (most recent call last):
  File "/home/xll/miniconda3/envs/musetalk/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/xll/miniconda3/envs/musetalk/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xll/MuseTalk/scripts/realtime_inference.py", line 215, in process_frames
    combine_frame = get_image_blending(ori_frame,res_frame,bbox,mask,mask_crop_box)
  File "/home/xll/MuseTalk/musetalk/utils/blending.py", line 93, in get_image_blending
    face_large[y-y_s:y1-y_s, x-x_s:x1-x_s]=face
ValueError: could not broadcast input array from shape (330,261,3) into shape (330,0,3)
100%|███████████████████████████████████████████████████████████| 136/136 [00:12<00:00, 10.66it/s]
Total process time of 541 frames without saving images = 12.757274866104126s
```
貌似是face对象的第二个维度出现问题？请问应该如何解决

**Comment by BIGshuaishuaishuai** [comment]
```
            mask = self.mask_list_cycle[self.idx%(len(self.mask_list_cycle))]
            mask_crop_box = self.mask_coords_list_cycle[self.idx%(len(self.mask_coords_list_cycle))]
            #combine_frame = get_image(ori_frame,res_frame,bbox)
            combine_frame = get_image_blending(ori_frame,res_frame,bbox,mask,mask_crop_box)
```
我检查了一下，`mask_crop_box`这个bbox存在负数的坐标，导致后续`get_image_blending`切片时索引错误，为什么会产生这样的负数坐标？

**Comment by praymich** [comment]
请问你解决了吗？我也遇到这个问题了

**Comment by BIGshuaishuaishuai** [comment]
> 请问你解决了吗？我也遇到这个问题了

作者这部分代码可能写的不是很严谨，可以参考这个回答把代码改一下|
https://github.com/TMElyralab/MuseTalk/issues/220#issuecomment-2467139770

另外注意把输入图像脸占画幅的比重缩小一点，离边框远一点。我之前这里出现负数就是因为经过扩散过程后，生成图像脸的像素位置变了，可能越过边框，导致数组溢出
