### ISSUE TITLE
dependency conflict: diffusers are fixed at version that uses older hugginface than other libs

### ISSUE THREAD

**Issue by antonkulaga** [TMElyralab/MuseTalk#234]
```python app.py
Already download the model.
please download ffmpeg-static and export to FFMPEG_PATH. 
For example: export FFMPEG_PATH=/musetalk/ffmpeg-4.4-amd64-static
Traceback (most recent call last):
  File "/home/antonkulaga/sources/MuseTalk/app.py", line 119, in <module>
    from musetalk.utils.utils import get_file_type,get_video_fps,datagen
  File "/home/antonkulaga/sources/MuseTalk/musetalk/utils/utils.py", line 15, in <module>
    from musetalk.models.vae import VAE
  File "/home/antonkulaga/sources/MuseTalk/musetalk/models/vae.py", line 1, in <module>
    from diffusers import AutoencoderKL
  File "/home/antonkulaga/micromamba/envs/muse/lib/python3.11/site-packages/diffusers/__init__.py", line 5, in <module>
    from .utils import (
  File "/home/antonkulaga/micromamba/envs/muse/lib/python3.11/site-packages/diffusers/utils/__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "/home/antonkulaga/micromamba/envs/muse/lib/python3.11/site-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/home/antonkulaga/micromamba/envs/muse/lib/python3.11/site-packages/huggingface_hub/__init__.py)

**Comment by syghhhhh** [comment]
pip install huggingface_hub==0.25.2
