### ISSUE TITLE
用 realtime 模式生成 avator 会产生错误

### ISSUE THREAD

**Issue by MrWangMrsLu** [TMElyralab/MuseTalk#237]
1、修改configs/inference/realtime.yaml
avator_1:
 preparation: True
 bbox_shift: 5
 video_path: "data/video/yongen.mp4"
 audio_clips:
     audio_0: "data/audio/yongen.wav"
     audio_1: "data/audio/sun.wav"

2、执行
python -m scripts.realtime_inference --inference_config configs/inference/realtime.yaml

3、报错
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 141/141 [00:45<00:00,  3.11it/s]
Total process time of 564 frames including saving images = 45.40461015701294s
ffmpeg -y -v warning -r 25 -f image2 -i ./results/avatars/avator_1/tmp/%08d.png -vcodec libx264 -vf format=rgb24,scale=out_color_matrix=bt709,format=yuv420p -crf 18 ./results/avatars/avator_1/temp.mp4
[image2 @ 0x5b1b100] Could find no file with path './results/avatars/avator_1/tmp/%08d.png' and index in the range 0-4
./results/avatars/avator_1/tmp/%08d.png: No such file or directory
ffmpeg -y -v warning -i data/audio/sun.wav -i ./results/avatars/avator_1/temp.mp4 ./results/avatars/avator_1/vid_output/audio_1.mp4
Guessed Channel Layout for Input Stream #0.0 : mono
./results/avatars/avator_1/temp.mp4: No such file or directory
Traceback (most recent call last):
  File "/home/ubuntu/software/conda/envs/musetalk/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/software/conda/envs/musetalk/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/software/MuseTalk-main/scripts/realtime_inference.py", line 332, in <module>
    avatar.inference(audio_path, 
  File "/home/ubuntu/software/MuseTalk-main/scripts/realtime_inference.py", line 283, in inference
    os.remove(f"{self.avatar_path}/temp.mp4")
FileNotFoundError: [Errno 2] No such file or directory: './results/avatars/avator_1/temp.mp4'

**Comment by MrWangMrsLu** [comment]
引起这个错误的原因是因为上面报了opencv的错，解决方式见：https://github.com/TMElyralab/MuseTalk/issues/220
