### ISSUE TITLE
KeyError: 'Event not found in queue. If you are deploying this Gradio app with multiple replicas, please enable stickiness to ensure that all requests from the same user are routed to the same instance.'

### ISSUE THREAD

**Issue by yy1844** [TMElyralab/MuseTalk#57]
Traceback (most recent call last):
  File "E:\MuseTalk\.glut\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "E:\MuseTalk\.glut\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "E:\MuseTalk\.glut\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "E:\MuseTalk\.glut\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "E:\MuseTalk\.glut\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "E:\MuseTalk\.glut\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "E:\MuseTalk\.glut\lib\site-packages\gradio\route_utils.py", line 695, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "E:\MuseTalk\.glut\lib\site-packages\gradio\route_utils.py", line 711, in simple_response
    await self.app(scope, receive, send)
  File "E:\MuseTalk\.glut\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "E:\MuseTalk\.glut\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "E:\MuseTalk\.glut\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "E:\MuseTalk\.glut\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "E:\MuseTalk\.glut\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "E:\MuseTalk\.glut\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "E:\MuseTalk\.glut\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "E:\MuseTalk\.glut\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "E:\MuseTalk\.glut\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "E:\MuseTalk\.glut\lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
  File "E:\MuseTalk\.glut\lib\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "E:\MuseTalk\.glut\lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "E:\MuseTalk\.glut\lib\site-packages\gradio\routes.py", line 737, in queue_join
    return await queue_join_helper(body, request, username)
  File "E:\MuseTalk\.glut\lib\site-packages\gradio\routes.py", line 755, in queue_join_helper
    success, event_id = await blocks._queue.push(
  File "E:\MuseTalk\.glut\lib\site-packages\gradio\queueing.py", line 225, in push
    raise KeyError(
KeyError: 'Event not found in queue. If you are deploying this Gradio app with multiple replicas, please enable stickiness to ensure that all requests from the same user are routed to the same instance.'
使用的是一键包。python3.12，cuda12.1。求救

**Comment by ibrahim737701** [comment]
Same issue

**Comment by WillowRw** [comment]
Same issue. Have you solved it ?

**Comment by WillowRw** [comment]
pip install gradio==3.50.2 In web_demo_2.5.py, change it to `demo.launch(share=True, enable_queue=False, debug=True, show_api=False, server_port=8080, server_name="0.0.0.0")`
