### ISSUE TITLE
python app.py报错

### ISSUE THREAD

**Issue by ltbjwzttzz** [TMElyralab/MuseTalk#71]
(venv) e:\AI\MuseTalk>python app.py
Traceback (most recent call last):
  File "e:\AI\MuseTalk\app.py", line 7, in <module>
    import spaces
  File "e:\AI\MuseTalk\venv\lib\site-packages\spaces\__init__.py", line 10, in <module>
    from .zero.decorator import GPU
  File "e:\AI\MuseTalk\venv\lib\site-packages\spaces\zero\decorator.py", line 21, in <module>
    from .wrappers import regular_function_wrapper
  File "e:\AI\MuseTalk\venv\lib\site-packages\spaces\zero\wrappers.py", line 14, in <module>
    from multiprocessing.context import ForkProcess
ImportError: cannot import name 'ForkProcess' from 'multiprocessing.context' (C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py)

环境是win10 ，Python 3.10.6。
在requirements.txt把spaces修改为spaces==0.25.0，依然报错。

**Comment by herolj** [comment]
你好，解决了吗，和你一样问题

**Comment by YangQuGithub** [comment]
参照：https://blog.csdn.net/weixin_43935971/article/details/138626446，启动成功。http://127.0.0.1:7860
