### ISSUE TITLE
【合成报错】PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'temp.mp4'

### ISSUE THREAD

**Issue by Ikaros-521** [TMElyralab/MuseTalk#78]
```
video in 25.0 FPS, audio idx in 50FPS
extracting landmarks...time consuming
reading images...
get key_landmark and face bounding boxes with the default value
********************************************bbox_shift parameter adjustment**********************************************************
Total frame:「268」 Manually adjust range : [ -22~23 ] , the current value: 0
*************************************************************************************************************************************
reading images...
get key_landmark and face bounding boxes with the default value
start inference
pad talking image to original video
202
Moviepy - Building video ./results/output\outputxxx_yongen_yongen.mp4.
MoviePy - Writing audio in outputxxx_yongen_yongenTEMP_MPY_wvf_snd.mp4
MoviePy - Done.
Moviepy - Writing video ./results/output\outputxxx_yongen_yongen.mp4

Moviepy - Done !
Moviepy - video ready ./results/output\outputxxx_yongen_yongen.mp4
Traceback (most recent call last):
  File "F:\MuseTalk\.glut\lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "F:\MuseTalk\.glut\lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "F:\MuseTalk\.glut\lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
  File "F:\MuseTalk\.glut\lib\site-packages\gradio\blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\MuseTalk\.glut\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "F:\MuseTalk\.glut\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "F:\MuseTalk\.glut\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "F:\MuseTalk\.glut\lib\site-packages\gradio\utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
  File "F:\MuseTalk\.glut\lib\site-packages\gradio\utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
  File "F:\MuseTalk\.glut\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\MuseTalk\app.py", line 310, in inference
    os.remove("temp.mp4")
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'temp.mp4'
```

**Comment by Ikaros-521** [comment]
![image](https://github.com/TMElyralab/MuseTalk/assets/40910637/e3df270e-df44-4cff-a7bf-a3abdec713ca)
暂时给删除注释了
