### ISSUE TITLE
MacBook M1 Pro 14" / MacOS 14.4.1 / Python 3.10.14 / 4152: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

### ISSUE THREAD

**Issue by git-zengmiao** [TMElyralab/MuseTalk#82]
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/musetalk/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Caskroom/miniconda/base/envs/musetalk/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/mark/Programs.localized/Projects/MuseTalk/scripts/inference.py", line 161, in <module>
    main(args)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/musetalk/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/mark/Programs.localized/Projects/MuseTalk/scripts/inference.py", line 90, in main
    crop_frame = cv2.resize(crop_frame,(256,256),interpolation = cv2.INTER_LANCZOS4)
cv2.error: OpenCV(4.9.0) /Users/xperience/GHA-OpenCV-Python2/_work/opencv-python/opencv-python/opencv/modules/imgproc/src/resize.cpp:4152: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

**Comment by alexLIUMinhao** [comment]
Hi，

The error you encountered may occur because the input image "**crop_frame**" is **empty** or **invalid** when attempting to resize it. Please check your input data to ensure that it has been cropped correctly.

**Comment by ArlanCooper** [comment]
我也是，但是加载案例是没有这个问题的，就是加载自己通过museV生成的视频，会导致这个问题，
```
video in 50.0 FPS, audio idx in 50FPS
extracting landmarks...time consuming
reading images...
100%|██████████████████████████████████████████████████████████████████████████| 251/251 [00:00<00:00, 297.82it/s]
get key_landmark and face bounding boxes with the bbox_shift: -7
100%|███████████████████████████████████████████████████████████████████████████| 251/251 [00:08<00:00, 31.24it/s]
********************************************bbox_shift parameter adjustment**********************************************************
Total frame:「251」 Manually adjust range : [ -4~4 ] , the current value: -7
*************************************************************************************************************************************
Traceback (most recent call last):
  File "/home/powerop/work/conda/envs/mymusetalk/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/powerop/work/conda/envs/mymusetalk/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/powerop/work/rwq/hackthon/MuseTalk/scripts/inference.py", line 161, in <module>
    main(args)
  File "/home/powerop/work/conda/envs/mymusetalk/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/powerop/work/rwq/hackthon/MuseTalk/scripts/inference.py", line 90, in main
    crop_frame = cv2.resize(crop_frame,(256,256),interpolation = cv2.INTER_LANCZOS4)
cv2.error: OpenCV(4.9.0) /io/opencv/modules/imgproc/src/resize.cpp:4152: error: (-215:Assertion failed) !ssize.empty() in function 'resize'


```

为什么我生成的帧数是只有251，这里是在哪里设置的呢？
